import { ArticleCard } from "@/components/public/ArticleCard";
import { PublicShell } from "@/components/public/PublicShell";
import { Button } from "@/components/ui/button";
import { Loader2, Tags } from "lucide-react";
import { useMemo } from "react";
import { Link, useRoute } from "wouter";
import { trpc } from "@/lib/trpc";

function Listing({ eyebrow, title, description, input }: { eyebrow: string; title: string; description: string; input: { category?: string; tag?: string; year?: number; page: number } }) {
  const posts = trpc.blog.list.useQuery(input);
  return <PublicShell><section className="border-b border-border bg-[#e8ede6]"><div className="container max-w-5xl py-14 md:py-20"><p className="font-label text-[10px] text-primary">{eyebrow}</p><h1 className="mt-3 font-display text-5xl font-semibold tracking-tight md:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-muted-foreground">{description}</p></div></section><section className="container py-12 md:py-16">{posts.isLoading ? <div className="grid min-h-64 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div> : posts.isError ? <div className="rounded-xl border border-dashed border-destructive/40 p-12 text-center"><p className="font-display text-2xl">These stories could not load.</p><Button className="mt-4" variant="outline" onClick={() => posts.refetch()}>Try again</Button></div> : posts.data?.items.length ? <div className="grid gap-x-7 gap-y-12 md:grid-cols-3">{posts.data.items.map(post => <ArticleCard key={post.id} post={post} />)}</div> : <div className="rounded-xl border border-dashed border-border bg-white p-14 text-center"><p className="font-display text-2xl">No published stories are here yet.</p><p className="mt-2 text-sm text-muted-foreground">Explore another topic or return soon.</p><Link href="/" className="mt-5 inline-block text-sm font-semibold text-primary">Browse all stories</Link></div>}</section></PublicShell>;
}

export function TopicArchive() { const [, params] = useRoute("/topics/:slug"); const slug = params?.slug || ""; const categories = trpc.blog.categories.useQuery(); const category = categories.data?.find(item => item.slug === slug); const input = useMemo(() => ({ category: slug || undefined, page: 1 }), [slug]); return <Listing eyebrow="Topic" title={category?.name || "Topic"} description={category?.description || "A collection of published stories organized around a shared editorial theme."} input={input} />; }
export function TagArchive() { const [, params] = useRoute("/tags/:slug"); const slug = params?.slug || ""; const tags = trpc.blog.tags.useQuery(); const tag = tags.data?.find(item => item.slug === slug); const input = useMemo(() => ({ tag: slug || undefined, page: 1 }), [slug]); return <Listing eyebrow="Tag" title={tag ? `#${tag.name}` : "Tag"} description="Published stories connected by a specific idea, thread, or subject." input={input} />; }
export function PublicationArchive() { const archives = trpc.blog.archives.useQuery(); return <PublicShell><section className="border-b border-border bg-[#e8ede6]"><div className="container max-w-5xl py-14 md:py-20"><p className="font-label text-[10px] text-primary">Publication archive</p><h1 className="mt-3 font-display text-5xl font-semibold tracking-tight md:text-6xl">By the year.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-muted-foreground">A chronological map of every published Fieldnote story.</p></div></section><section className="container max-w-5xl py-12 md:py-16">{archives.isLoading ? <div className="grid min-h-48 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div> : archives.data?.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{archives.data.map(item => <Link key={item.year} href={`/archive/${item.year}`} className="group rounded-xl border border-border bg-white p-6 shadow-sm transition hover:border-primary"><div className="flex items-center justify-between"><span className="font-display text-4xl font-semibold">{item.year}</span><Tags className="h-5 w-5 text-primary" /></div><p className="mt-5 text-sm text-muted-foreground">{item.count} {item.count === 1 ? "published story" : "published stories"}</p></Link>)}</div> : <p className="rounded-xl border border-dashed border-border p-12 text-center text-sm text-muted-foreground">The archive will appear after the first story is published.</p>}</section></PublicShell>; }
export function YearArchive() { const [, params] = useRoute("/archive/:year"); const year = Number(params?.year); const input = useMemo(() => ({ year: Number.isFinite(year) ? year : undefined, page: 1 }), [year]); return <Listing eyebrow="Publication archive" title={Number.isFinite(year) ? String(year) : "Archive"} description="Published Fieldnote stories from this year." input={input} />; }
