import DashboardLayout from "@/admin-site/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Download, Loader2, Plus, ScrollText, Settings2, ShieldCheck, UploadCloud, UsersRound } from "lucide-react";
import { ChangeEvent, useEffect, useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";

function Frame({ title, eyebrow, children, actions }: { title: string; eyebrow?: string; children: React.ReactNode; actions?: React.ReactNode }) {
  const bootstrap = trpc.studio.bootstrap.useQuery();
  return <DashboardLayout><div className="mx-auto max-w-7xl"><header className="mb-7 flex flex-col gap-4 border-b border-border pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-label text-[10px] text-primary">{eyebrow || bootstrap.data?.site?.name || "Editorial workspace"}</p><h1 className="mt-2 font-display text-4xl font-semibold tracking-tight">{title}</h1></div>{actions}</header>{bootstrap.isLoading ? <div className="grid min-h-64 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div> : children}</div></DashboardLayout>;
}

const stateStyles: Record<string, string> = { draft: "bg-slate-100 text-slate-700", review: "bg-amber-100 text-amber-800", published: "bg-emerald-100 text-emerald-800", archived: "bg-stone-200 text-stone-700" };
export const StatusPill = ({ state }: { state: string }) => <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-medium capitalize ${stateStyles[state] || "bg-muted"}`}>{state}</span>;

export function StudioOverview() {
  const posts = trpc.studio.posts.list.useQuery({}); const analytics = trpc.studio.analytics.useQuery({});
  const current = posts.data ?? []; const counts = ["draft", "review", "published", "archived"].map(status => ({ status, count: current.filter(post => post.status === status).length }));
  return <Frame title="Editorial overview" eyebrow="Your publication, at a glance" actions={<Link href="/studio/posts/new"><Button className="gap-2"><Plus className="h-4 w-4" />New post</Button></Link>}><div className="grid gap-4 md:grid-cols-4">{counts.map(item => <div key={item.status} className="rounded-xl border border-border bg-white p-5 shadow-sm"><p className="font-label text-[10px] text-muted-foreground">{item.status}</p><p className="mt-3 font-display text-4xl font-semibold">{item.count}</p></div>)}</div><div className="mt-7 grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><section className="rounded-xl border border-border bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="font-label text-[10px] text-primary">Review queue</p><h2 className="mt-2 font-display text-2xl font-semibold">Awaiting an editorial decision</h2></div><Link href="/studio/posts" className="text-sm font-medium text-primary">View all</Link></div><div className="mt-5 divide-y divide-border">{current.filter(post => post.status === "review").slice(0, 5).map(post => <Link key={post.id} href={`/studio/posts/${post.id}`} className="flex items-center justify-between gap-4 py-4 hover:text-primary"><div><p className="font-medium">{post.title}</p><p className="mt-1 text-xs text-muted-foreground">Submitted {post.submitted_at ? new Date(post.submitted_at).toLocaleDateString() : "recently"}</p></div><StatusPill state={post.status} /></Link>)}{!current.some(post => post.status === "review") && <p className="py-10 text-center text-sm text-muted-foreground">Nothing is waiting for review.</p>}</div></section><section className="rounded-xl bg-[#1b382d] p-6 text-[#edf4ea]"><p className="font-label text-[10px] text-[#abc8b2]">Last 30 days</p><p className="mt-3 font-display text-5xl font-semibold">{analytics.data?.totalViews ?? 0}</p><p className="mt-1 text-sm text-[#c6d5ca]">Measured page views</p><div className="mt-8 border-t border-[#396550] pt-5"><p className="text-sm font-medium">{analytics.data?.engagementRate ?? 0}% engagement rate</p><p className="mt-1 text-xs leading-5 text-[#abc8b2]">Engagement is calculated from meaningful reading, scroll, comment, and subscription events.</p></div></section></div></Frame>;
}

export function StudioPosts() {
  const [status, setStatus] = useState<string>("all"); const [search, setSearch] = useState(""); const list = trpc.studio.posts.list.useQuery({ status: status === "all" ? undefined : status as "draft" | "review" | "published" | "archived", search: search || undefined });
  return <Frame title="Posts" eyebrow="Plan, write, review, publish" actions={<Link href="/studio/posts/new"><Button className="gap-2"><Plus className="h-4 w-4" />New post</Button></Link>}><div className="mb-5 flex flex-col gap-3 sm:flex-row"><Input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search your posts" className="max-w-md bg-white" /><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-full bg-white sm:w-40"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All states</SelectItem><SelectItem value="draft">Draft</SelectItem><SelectItem value="review">Review</SelectItem><SelectItem value="published">Published</SelectItem><SelectItem value="archived">Archived</SelectItem></SelectContent></Select></div><div className="overflow-hidden rounded-xl border border-border bg-white shadow-sm"><div className="hidden grid-cols-[1fr_130px_140px] gap-4 border-b border-border bg-[#fbfcfa] px-5 py-3 font-label text-[10px] text-muted-foreground md:grid"><span>Story</span><span>Status</span><span>Updated</span></div>{list.isLoading ? <div className="grid min-h-48 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div> : list.data?.length ? list.data.map(post => <Link key={post.id} href={`/studio/posts/${post.id}`} className="grid gap-3 border-b border-border px-5 py-4 last:border-b-0 hover:bg-[#fbfcfa] md:grid-cols-[1fr_130px_140px] md:items-center"><div><p className="font-medium">{post.title}</p><p className="mt-1 line-clamp-1 text-xs text-muted-foreground">{post.excerpt || "No excerpt yet"}</p></div><div><StatusPill state={post.status} /></div><time className="text-xs text-muted-foreground">{new Date(post.updated_at).toLocaleDateString()}</time></Link>) : <p className="p-12 text-center text-sm text-muted-foreground">No posts match these filters.</p>}</div></Frame>;
}

const fileToBase64 = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error("Could not read the file.")); reader.readAsDataURL(file); });
export function StudioMedia() {
  const [folder, setFolder] = useState("library"); const [folderFilter, setFolderFilter] = useState("");
  const media = trpc.studio.media.list.useQuery({ folder: folderFilter || undefined }); const upload = trpc.studio.media.upload.useMutation({ onSuccess: () => { media.refetch(); toast.success("Media uploaded to the library."); }, onError: error => toast.error(error.message) });
  const onUpload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.currentTarget.value = ""; if (!file) return; const allowed = ["image/jpeg", "image/png", "image/webp", "image/gif", "image/svg+xml", "application/pdf"]; if (!allowed.includes(file.type) || file.size > 10 * 1024 * 1024) { toast.error("Choose an accepted file smaller than 10 MB."); return; } upload.mutate({ filename: file.name, mimeType: file.type as "image/jpeg" | "image/png" | "image/webp" | "image/gif" | "image/svg+xml" | "application/pdf", base64: await fileToBase64(file), folder: folder.trim() || "library", altText: "" }); };
  return <Frame title="Media library" eyebrow="S3-backed, reusable assets" actions={<label><input className="hidden" type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/svg+xml,application/pdf" onChange={onUpload} /><Button asChild className="gap-2"><span><UploadCloud className="h-4 w-4" />Upload asset</span></Button></label>}><p className="mb-5 text-sm text-muted-foreground">Images and documents are kept in centralized object storage and referenced through durable delivery URLs.</p><div className="mb-5 grid gap-3 rounded-xl border border-border bg-white p-4 sm:grid-cols-2"><div><p className="mb-1.5 text-xs font-medium text-muted-foreground">Upload into folder</p><Input value={folder} onChange={event => setFolder(event.target.value)} placeholder="e.g. issue-01" /></div><div><p className="mb-1.5 text-xs font-medium text-muted-foreground">Filter library folder</p><Input value={folderFilter} onChange={event => setFolderFilter(event.target.value)} placeholder="All folders" /></div></div>{media.isLoading ? <div className="grid min-h-48 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div> : media.data?.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{media.data.map(asset => <div key={asset.id} className="overflow-hidden rounded-xl border border-border bg-white"><div className="aspect-[4/3] bg-secondary">{asset.mime_type.startsWith("image/") ? <img src={asset.url} alt={asset.alt_text || ""} className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center text-sm text-muted-foreground">{asset.mime_type}</div>}</div><div className="p-3"><p className="truncate text-sm font-medium">{asset.filename}</p><p className="mt-1 text-xs text-muted-foreground">{Math.ceil(asset.byte_size / 1024)} KB · {asset.folder}</p></div></div>)}</div> : <div className="rounded-xl border border-dashed border-border bg-white p-14 text-center"><UploadCloud className="mx-auto h-7 w-7 text-primary" /><p className="mt-3 font-display text-2xl">Your library is ready for its first asset.</p><p className="mt-2 text-sm text-muted-foreground">Upload a supported image or document to reuse it across posts.</p></div>}</Frame>;
}

export function StudioTaxonomy() {
  const taxonomy = trpc.studio.taxonomy.list.useQuery(); const [category, setCategory] = useState(""); const [tag, setTag] = useState(""); const createCategory = trpc.studio.taxonomy.createCategory.useMutation({ onSuccess: () => { setCategory(""); taxonomy.refetch(); toast.success("Category created."); }, onError: error => toast.error(error.message) }); const createTag = trpc.studio.taxonomy.createTag.useMutation({ onSuccess: () => { setTag(""); taxonomy.refetch(); toast.success("Tag created."); }, onError: error => toast.error(error.message) });
  return <Frame title="Taxonomy" eyebrow="Categories and tags"><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl border border-border bg-white p-6 shadow-sm"><p className="font-label text-[10px] text-primary">Categories</p><h2 className="mt-2 font-display text-2xl font-semibold">Big editorial beats</h2><form className="mt-5 flex gap-2" onSubmit={event => { event.preventDefault(); if (category.trim()) createCategory.mutate({ name: category }); }}><Input value={category} onChange={event => setCategory(event.target.value)} placeholder="e.g. Culture" /><Button type="submit" disabled={createCategory.isPending}>Add</Button></form><div className="mt-5 space-y-2">{taxonomy.data?.categories.map(item => <div key={item.id} className="flex items-center justify-between rounded-lg bg-muted/60 px-3 py-2"><span className="text-sm font-medium">{item.name}</span><span className="font-label text-[10px] text-muted-foreground">/{item.slug}</span></div>)}{!taxonomy.data?.categories.length && <p className="py-6 text-sm text-muted-foreground">No categories yet.</p>}</div></section><section className="rounded-xl border border-border bg-white p-6 shadow-sm"><p className="font-label text-[10px] text-primary">Tags</p><h2 className="mt-2 font-display text-2xl font-semibold">Specific ideas and threads</h2><form className="mt-5 flex gap-2" onSubmit={event => { event.preventDefault(); if (tag.trim()) createTag.mutate({ name: tag }); }}><Input value={tag} onChange={event => setTag(event.target.value)} placeholder="e.g. decision-making" /><Button type="submit" disabled={createTag.isPending}>Add</Button></form><div className="mt-5 flex flex-wrap gap-2">{taxonomy.data?.tags.map(item => <span key={item.id} className="rounded-full border border-border px-3 py-1.5 text-sm">#{item.name}</span>)}{!taxonomy.data?.tags.length && <p className="py-6 text-sm text-muted-foreground">No tags yet.</p>}</div></section></div></Frame>;
}

export function StudioModeration() {
  const queue = trpc.studio.moderation.list.useQuery({ status: "pending" }); const resolve = trpc.studio.moderation.resolve.useMutation({ onSuccess: () => { queue.refetch(); toast.success("Comment moderation updated."); }, onError: error => toast.error(error.message) });
  return <Frame title="Moderation" eyebrow="Reader conversation"><div className="rounded-xl border border-border bg-white shadow-sm">{queue.isLoading ? <div className="grid min-h-48 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div> : queue.data?.length ? queue.data.map(comment => <div key={comment.id} className="border-b border-border p-5 last:border-b-0"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold">{comment.author_name} <span className="font-normal text-muted-foreground">on {comment.posts?.title || "an article"}</span></p><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{comment.body}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => resolve.mutate({ id: comment.id, status: "rejected" })}>Reject</Button><Button size="sm" variant="destructive" onClick={() => resolve.mutate({ id: comment.id, status: "deleted" })}>Delete</Button><Button size="sm" onClick={() => resolve.mutate({ id: comment.id, status: "approved" })}>Approve</Button></div></div></div>) : <p className="p-14 text-center text-sm text-muted-foreground">The moderation queue is clear.</p>}</div></Frame>;
}

export function StudioAnalytics() { const analytics = trpc.studio.analytics.useQuery({}); return <Frame title="Analytics" eyebrow="Reader engagement"><div className="grid gap-4 md:grid-cols-3"><Metric label="Page views" value={analytics.data?.totalViews ?? 0} /><Metric label="Engagement events" value={analytics.data?.engagementEvents ?? 0} /><Metric label="Engagement rate" value={`${analytics.data?.engagementRate ?? 0}%`} /></div><section className="mt-7 rounded-xl border border-border bg-white p-6 shadow-sm"><p className="font-label text-[10px] text-primary">Top stories</p><h2 className="mt-2 font-display text-2xl font-semibold">What readers are engaging with</h2><div className="mt-5 divide-y divide-border">{analytics.data?.topPosts.length ? analytics.data.topPosts.map((post, index) => <div key={post.postId} className="grid grid-cols-[32px_1fr_auto] gap-3 py-4"><span className="font-display text-xl text-primary">{index + 1}</span><div><p className="font-medium">{post.title}</p><p className="mt-1 text-xs text-muted-foreground">/{post.slug || "draft"}</p></div><div className="text-right"><p className="text-sm font-semibold">{post.views}</p><p className="text-xs text-muted-foreground">views</p></div></div>) : <p className="py-10 text-center text-sm text-muted-foreground">Analytics will appear as readers interact with published content.</p>}</div></section></Frame>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl border border-border bg-white p-5 shadow-sm"><p className="font-label text-[10px] text-muted-foreground">{label}</p><p className="mt-3 font-display text-4xl font-semibold">{value}</p></div>; }

export function StudioTeam() { const people = trpc.studio.people.list.useQuery(); const changeRole = trpc.studio.people.changeRole.useMutation({ onSuccess: () => { people.refetch(); toast.success("Editorial role updated."); }, onError: error => toast.error(error.message) }); return <Frame title="Editorial team" eyebrow="Role-based access"><section className="rounded-xl border border-border bg-white shadow-sm"><div className="border-b border-border p-5"><div className="flex items-center gap-3"><UsersRound className="h-5 w-5 text-primary" /><div><h2 className="font-display text-2xl font-semibold">Publication members</h2><p className="mt-1 text-sm text-muted-foreground">Admins can manage roles. Authors can edit their own posts; Editors can review and publish.</p></div></div></div>{people.data?.map(member => { const profile = (member.profiles as unknown as Array<{ display_name: string | null; email: string | null }> | null)?.[0]; return <div key={member.id} className="flex flex-col gap-3 border-b border-border p-5 last:border-b-0 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{profile?.display_name || "Editorial member"}</p><p className="mt-1 text-xs text-muted-foreground">{profile?.email || "No email available"}</p></div><Select value={member.role} onValueChange={role => changeRole.mutate({ membershipId: member.id, role: role as "admin" | "editor" | "author" })}><SelectTrigger className="w-full bg-white sm:w-36"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="admin">Admin</SelectItem><SelectItem value="editor">Editor</SelectItem><SelectItem value="author">Author</SelectItem></SelectContent></Select></div>; })}{!people.data?.length && <p className="p-12 text-center text-sm text-muted-foreground">No members have signed into this publication yet.</p>}</section></Frame>; }

export function StudioNotifications() { const outbox = trpc.studio.notifications.useQuery(); return <Frame title="Notification outbox" eyebrow="Role-targeted delivery"><p className="mb-5 text-sm text-muted-foreground">Workflow actions write auditable notification records. Connect an email provider in production to dispatch pending items.</p><section className="overflow-hidden rounded-xl border border-border bg-white shadow-sm">{outbox.data?.length ? outbox.data.map(item => <div key={item.id} className="grid gap-2 border-b border-border p-5 last:border-b-0 md:grid-cols-[1fr_150px_120px]"><div><p className="text-sm font-semibold">{item.subject}</p><p className="mt-1 text-xs text-muted-foreground">To {item.recipient_email}</p></div><p className="text-xs capitalize text-muted-foreground">{item.event_type.replaceAll("_", " ")}</p><StatusPill state={item.status} /></div>) : <p className="p-14 text-center text-sm text-muted-foreground">No workflow notifications are waiting.</p>}</section></Frame>; }

export function StudioSettings() {
  const settings = trpc.studio.settings.get.useQuery(); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [domain, setDomain] = useState(""); const [locale, setLocale] = useState("en"); const [timezone, setTimezone] = useState("UTC"); const [nav, setNav] = useState("[]"); const update = trpc.studio.settings.update.useMutation({ onSuccess: () => { settings.refetch(); toast.success("Publication settings saved and audited."); }, onError: error => toast.error(error.message) });
  useEffect(() => { if (settings.data) { setName(settings.data.site.name); setDescription(settings.data.site.description || ""); setDomain(settings.data.site.custom_domain || ""); setLocale(settings.data.settings?.default_locale || "en"); setTimezone(settings.data.settings?.timezone || "UTC"); setNav(JSON.stringify(settings.data.settings?.navigation || [], null, 2)); } }, [settings.data]);
  const save = () => { let navigation: Array<{ label: string; path: string }>; try { navigation = JSON.parse(nav); if (!Array.isArray(navigation)) throw new Error(); } catch { toast.error("Navigation must be a JSON array of { label, path } entries."); return; } update.mutate({ name, description: description || undefined, customDomain: domain || undefined, themeSettings: (settings.data?.site.theme_settings || {}) as Record<string, unknown>, navigation, defaultLocale: locale, timezone, seoDefaults: (settings.data?.settings?.seo_defaults || {}) as Record<string, unknown>, featureFlags: (settings.data?.settings?.feature_flags || {}) as Record<string, boolean> }); };
  return <Frame title="Publication settings" eyebrow="Scoped branding, navigation, and controls"><div className="grid gap-6 lg:grid-cols-[1.05fr_.95fr]"><section className="rounded-xl border border-border bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Settings2 className="h-5 w-5 text-primary" /><div><h2 className="font-display text-2xl font-semibold">Publication identity</h2><p className="text-sm text-muted-foreground">Changes are limited to this publication and recorded in the audit trail.</p></div></div><div className="mt-6 space-y-4"><div><label className="text-xs font-medium text-muted-foreground">Publication name</label><Input value={name} onChange={event => setName(event.target.value)} className="mt-1.5" /></div><div><label className="text-xs font-medium text-muted-foreground">Description</label><textarea value={description} onChange={event => setDescription(event.target.value)} rows={3} className="mt-1.5 flex w-full rounded-md border border-input bg-background px-3 py-2 text-sm" /></div><div><label className="text-xs font-medium text-muted-foreground">Custom domain</label><Input value={domain} onChange={event => setDomain(event.target.value)} placeholder="journal.example.com" className="mt-1.5" /><p className="mt-1 text-xs text-muted-foreground">Saving a domain stores the intended host. DNS, TLS, and verification remain external operations.</p></div><div className="grid gap-3 sm:grid-cols-2"><div><label className="text-xs font-medium text-muted-foreground">Locale</label><Input value={locale} onChange={event => setLocale(event.target.value)} className="mt-1.5" /></div><div><label className="text-xs font-medium text-muted-foreground">Timezone</label><Input value={timezone} onChange={event => setTimezone(event.target.value)} className="mt-1.5" /></div></div><Button onClick={save} disabled={update.isPending}>{update.isPending ? "Saving…" : "Save settings"}</Button></div></section><section className="rounded-xl border border-border bg-[#fbfcfa] p-6 shadow-sm"><p className="font-label text-[10px] text-primary">Navigation JSON</p><h2 className="mt-2 font-display text-2xl font-semibold">Explicit public links</h2><p className="mt-2 text-sm text-muted-foreground">Use a JSON array such as <code>[&#123;"label":"Topics","path":"/topics"&#125;]</code>.</p><textarea value={nav} onChange={event => setNav(event.target.value)} rows={15} className="mt-5 w-full rounded-lg border border-border bg-white p-3 font-mono text-xs leading-5" /><div className="mt-4 rounded-lg border border-[#d6e2d1] bg-[#eff6ec] p-4 text-sm text-[#31513d]">Theme and feature-flag records are intentionally stored as structured site-scoped configuration. Advanced visual-builder controls will use the same safe settings boundary.</div></section></div></Frame>;
}

export function StudioAudit() { const audit = trpc.studio.audit.list.useQuery({}); return <Frame title="Audit log" eyebrow="Traceable privileged activity"><section className="overflow-hidden rounded-xl border border-border bg-white shadow-sm">{audit.isLoading ? <div className="grid min-h-48 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div> : audit.data?.length ? audit.data.map(event => { const actor = (event.profiles as unknown as Array<{ display_name?: string | null; email?: string | null }> | null)?.[0]; return <div key={event.id} className="grid gap-3 border-b border-border p-5 last:border-b-0 md:grid-cols-[1.2fr_.7fr_.8fr]"><div><p className="font-medium">{event.action.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-muted-foreground">{actor?.display_name || actor?.email || "System actor"} · {event.resource_type}</p></div><pre className="overflow-x-auto rounded bg-muted p-2 text-[10px] text-muted-foreground">{JSON.stringify(event.metadata)}</pre><time className="text-xs text-muted-foreground">{new Date(event.created_at).toLocaleString()}</time></div>; }) : <p className="p-14 text-center text-sm text-muted-foreground">No scoped audit events have been recorded yet.</p>}</section></Frame>; }

export function StudioCapabilities() { const capabilities = trpc.studio.capabilities.list.useQuery(); const setPolicy = trpc.studio.capabilities.set.useMutation({ onSuccess: () => { capabilities.refetch(); toast.success("Capability policy updated and audited."); }, onError: error => toast.error(error.message) }); const existing = (role: string, capabilityId: string) => capabilities.data?.policy.find(item => item.role === role && item.capability_id === capabilityId)?.allowed; return <Frame title="Capability policy" eyebrow="Role controls"><p className="mb-5 text-sm text-muted-foreground">Role permissions are server-enforced today. These scoped policy records establish an explicit, audited capability catalog for progressive enterprise controls.</p><section className="overflow-x-auto rounded-xl border border-border bg-white shadow-sm"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-[#fbfcfa] font-label text-[10px] text-muted-foreground"><tr><th className="p-4">Capability</th><th className="p-4">Risk</th><th className="p-4">Author</th><th className="p-4">Editor</th><th className="p-4">Admin</th></tr></thead><tbody>{capabilities.data?.catalog.map(capability => <tr key={capability.id} className="border-t border-border"><td className="p-4"><p className="font-medium">{capability.capability_key}</p><p className="mt-1 text-xs text-muted-foreground">{capability.description}</p></td><td className="p-4 capitalize">{capability.risk_level}</td>{(["author", "editor", "admin"] as const).map(role => <td key={role} className="p-4"><Button size="sm" variant={existing(role, capability.id) === false ? "outline" : "secondary"} onClick={() => { if (window.confirm(`Record ${role} policy for ${capability.capability_key}?`)) setPolicy.mutate({ role, capabilityId: capability.id, allowed: existing(role, capability.id) === false, confirmed: true }); }}>{existing(role, capability.id) === false ? "Denied" : "Allowed"}</Button></td>)}</tr>)}</tbody></table></section></Frame>; }

export function StudioExport() { const [format, setFormat] = useState<"json" | "markdown">("json"); const exportQuery = trpc.studio.exportContent.useQuery({ format }, { enabled: false }); const download = async () => { const result = await exportQuery.refetch(); if (!result.data) { toast.error("The export could not be prepared."); return; } const blob = new Blob([result.data.content], { type: format === "json" ? "application/json" : "text/markdown" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `fieldnote-export.${format === "json" ? "json" : "md"}`; link.click(); URL.revokeObjectURL(url); toast.success("Content export downloaded and audited."); };
  return <Frame title="Content export" eyebrow="Portable publication data"><section className="max-w-2xl rounded-xl border border-border bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Download className="h-5 w-5 text-primary" /><div><h2 className="font-display text-2xl font-semibold">Download your publication</h2><p className="text-sm text-muted-foreground">Export posts, structured content, taxonomy, media metadata, and subscriber records scoped to this site.</p></div></div><div className="mt-6 flex flex-wrap gap-3"><Select value={format} onValueChange={value => setFormat(value as "json" | "markdown")}><SelectTrigger className="w-44"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="json">Structured JSON</SelectItem><SelectItem value="markdown">Markdown bundle</SelectItem></SelectContent></Select><Button onClick={download} disabled={exportQuery.isFetching} className="gap-2"><Download className="h-4 w-4" />{exportQuery.isFetching ? "Preparing…" : "Download export"}</Button></div><p className="mt-5 text-xs text-muted-foreground">Exports are created on demand; access is restricted to publication administrators and every request is audited.</p></section></Frame>; }
